<?php /** @var \CaptchaFox\Core\Block\CaptchaFox\Config $block */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?php
$serializedCaptchaFoxConfig = $block->getSerializedCaptchaFoxConfig();
$scriptString = <<<script
        window.captchafoxConfig = {$serializedCaptchaFoxConfig};
script;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
